<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ladan">

<title>The Impact of AI Execution Autonomy on User Task Performance and Intervention Behavior in Digital Workflows</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="ai-execution-autonomy-analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="ai-execution-autonomy-analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="ai-execution-autonomy-analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="ai-execution-autonomy-analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="ai-execution-autonomy-analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ai-execution-autonomy-analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="ai-execution-autonomy-analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ai-execution-autonomy-analysis_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ai-execution-autonomy-analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ai-execution-autonomy-analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ai-execution-autonomy-analysis_files/libs/bootstrap/bootstrap-8ffd5f67044e5306d9846f29df41dda5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="styles.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#theory" id="toc-theory" class="nav-link" data-scroll-target="#theory"><span class="header-section-number">2</span> Theory</a>
  <ul class="collapse">
  <li><a href="#ai-execution-autonomy" id="toc-ai-execution-autonomy" class="nav-link" data-scroll-target="#ai-execution-autonomy"><span class="header-section-number">2.1</span> AI Execution Autonomy</a></li>
  <li><a href="#user-task-performance" id="toc-user-task-performance" class="nav-link" data-scroll-target="#user-task-performance"><span class="header-section-number">2.2</span> User Task Performance</a></li>
  <li><a href="#intervention-behavior" id="toc-intervention-behavior" class="nav-link" data-scroll-target="#intervention-behavior"><span class="header-section-number">2.3</span> Intervention Behavior</a></li>
  <li><a href="#research-gap-and-hypotheses" id="toc-research-gap-and-hypotheses" class="nav-link" data-scroll-target="#research-gap-and-hypotheses"><span class="header-section-number">2.4</span> Research Gap and Hypotheses</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a>
  <ul class="collapse">
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design"><span class="header-section-number">3.1</span> Study Design</a></li>
  <li><a href="#prototype-and-logging" id="toc-prototype-and-logging" class="nav-link" data-scroll-target="#prototype-and-logging"><span class="header-section-number">3.2</span> Prototype and Logging</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables"><span class="header-section-number">3.3</span> Variables</a></li>
  <li><a href="#sample" id="toc-sample" class="nav-link" data-scroll-target="#sample"><span class="header-section-number">3.4</span> Sample</a></li>
  <li><a href="#measures" id="toc-measures" class="nav-link" data-scroll-target="#measures"><span class="header-section-number">3.5</span> Measures</a></li>
  <li><a href="#data-preparation-and-analysis" id="toc-data-preparation-and-analysis" class="nav-link" data-scroll-target="#data-preparation-and-analysis"><span class="header-section-number">3.6</span> Data Preparation and Analysis</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#h1-task-performance" id="toc-h1-task-performance" class="nav-link" data-scroll-target="#h1-task-performance"><span class="header-section-number">4.1</span> H1: Task Performance</a>
  <ul class="collapse">
  <li><a href="#completion-time" id="toc-completion-time" class="nav-link" data-scroll-target="#completion-time"><span class="header-section-number">4.1.1</span> Completion Time</a></li>
  <li><a href="#detected-errors" id="toc-detected-errors" class="nav-link" data-scroll-target="#detected-errors"><span class="header-section-number">4.1.2</span> Detected Errors</a></li>
  <li><a href="#task-completion-and-abandonment" id="toc-task-completion-and-abandonment" class="nav-link" data-scroll-target="#task-completion-and-abandonment"><span class="header-section-number">4.1.3</span> Task Completion and Abandonment</a></li>
  </ul></li>
  <li><a href="#h2-intervention-behavior" id="toc-h2-intervention-behavior" class="nav-link" data-scroll-target="#h2-intervention-behavior"><span class="header-section-number">4.2</span> H2: Intervention Behavior</a>
  <ul class="collapse">
  <li><a href="#intervention-occurrence" id="toc-intervention-occurrence" class="nav-link" data-scroll-target="#intervention-occurrence"><span class="header-section-number">4.2.1</span> Intervention Occurrence</a></li>
  <li><a href="#intervention-count" id="toc-intervention-count" class="nav-link" data-scroll-target="#intervention-count"><span class="header-section-number">4.2.2</span> Intervention Count</a></li>
  <li><a href="#types-of-intervention" id="toc-types-of-intervention" class="nav-link" data-scroll-target="#types-of-intervention"><span class="header-section-number">4.2.3</span> Types of Intervention</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">5</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#evaluation-of-hypotheses" id="toc-evaluation-of-hypotheses" class="nav-link" data-scroll-target="#evaluation-of-hypotheses"><span class="header-section-number">5.1</span> Evaluation of Hypotheses</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">5.2</span> Interpretation</a></li>
  <li><a href="#theoretical-contributions" id="toc-theoretical-contributions" class="nav-link" data-scroll-target="#theoretical-contributions"><span class="header-section-number">5.3</span> Theoretical Contributions</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">5.4</span> Limitations</a></li>
  <li><a href="#practical-implications" id="toc-practical-implications" class="nav-link" data-scroll-target="#practical-implications"><span class="header-section-number">5.5</span> Practical Implications</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">5.6</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#declaration-of-independence" id="toc-declaration-of-independence" class="nav-link" data-scroll-target="#declaration-of-independence">Declaration of Independence</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="ai-execution-autonomy-analysis.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Impact of AI Execution Autonomy on User Task Performance and Intervention Behavior in Digital Workflows</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ladan </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="summary" class="level1 unnumbered">
<h1 class="unnumbered">Summary</h1>
<p>As AI systems increasingly assume execution authority in digital workflows, understanding how different levels of autonomy affect user behavior becomes essential. This study examined the effects of AI execution autonomy on user task performance and intervention behavior in a controlled digital workflow. Using a between-subject experimental design, 160 participants who initiated the task were assigned to one of three autonomy conditions — Manual, Assistance, or Execution — and completed a structured exam registration task via a purpose-built web prototype. Behavioral data were captured through system-generated event logs, enabling objective measurement of task completion time, error occurrence, task abandonment, and intervention frequency. Results provided differentiated support for the proposed hypotheses. Higher levels of AI execution autonomy were associated with significantly shorter completion times, lower error occurrence, and lower task abandonment rates, particularly when comparing the Manual condition with the two system-supported conditions. Intervention occurrence did not differ significantly across conditions; however, intervention count was significantly lower in the Assistance and Execution conditions compared with Manual. Descriptive analysis further revealed that the form of intervention shifted from direct configuration edits in the Manual condition toward override and rejection actions in the system-supported conditions. These findings suggest that AI execution autonomy can improve task efficiency and reduce manual effort without fully removing the user from the interaction process. The results support a design perspective in which autonomy is calibrated to task structure and user control requirements rather than unconditionally maximized.</p>
</section>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Artificial intelligence (AI) systems are increasingly embedded in digital workflows and are evolving from tools that provide decision support toward systems capable of autonomously executing actions. In many contemporary applications, AI no longer functions merely as a source of information or recommendations but actively participates in shaping and executing decisions. This shift from assistance to autonomous execution fundamentally changes the distribution of control, responsibility, and risk between human users and technical systems (Endsley, 2017; Parasuraman et al., 2000).</p>
<p>The distribution of decision authority between humans and automated systems has long been a central concern in human–automation interaction research. Early work conceptualized automation as a continuum of autonomy, ranging from full human control to full system control, and showed that different levels of automation can significantly influence human performance, error behavior, and reliance on automated systems (Parasuraman et al., 2000; Sheridan &amp; Verplank, 1978). However, much of this research has primarily focused on assistive systems in which humans retain primary decision authority.</p>
<p>More recent research in human–computer interaction has increasingly emphasized subjective constructs such as trust, perceived usefulness, and user satisfaction. While these perspectives provide valuable insights, they offer limited understanding of how users behave in concrete task execution scenarios, particularly in systems where AI assumes execution authority. As a result, there remains a lack of empirical, behavior-based evidence on how execution autonomy affects observable task outcomes and user intervention behavior in real interaction contexts (Hoff &amp; Bashir, 2015; Lee &amp; See, 2004).</p>
<p>This study addresses this gap by investigating how different levels of AI execution autonomy affect user task performance and intervention behavior in AI-assisted digital workflows. Specifically, three autonomy levels are examined—manual, assistance, and execution—which represent distinct distributions of decision authority between the user and the system. The analysis focuses on measurable behavioral outcomes, including task completion time, detected errors, abandonment, and intervention frequency, enabling a systematic comparison across conditions.</p>
<p>This leads to the following research question: How does the level of AI execution autonomy affect user task performance and intervention behavior in AI-assisted digital workflows?</p>
<p>The study adopts a controlled experimental design in which user interactions are captured through system-generated logs. Instead of relying on self-reported measures, behavioral data is used to assess how users perform tasks and how often they intervene under different autonomy conditions. By operationalizing AI execution autonomy as a system-level property rather than as a feature of a specific model, the study isolates the effect of execution authority within a controlled task environment. This reflects how AI systems are typically implemented in real-world applications, where autonomy emerges from system design rather than from the underlying model alone.</p>
<p>The contribution of this study lies in providing a behaviorally grounded, log-based analysis of AI execution autonomy. By capturing real user interactions in a controlled setting, the study enables a systematic comparison of task performance and intervention behavior across autonomy levels. The findings contribute to a more empirical understanding of how autonomy shapes human–AI interaction and provide practical insights for designing AI-assisted systems that balance efficiency and user control.</p>
</section>
<section id="theory" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Theory</h1>
<section id="ai-execution-autonomy" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="ai-execution-autonomy"><span class="header-section-number">2.1</span> AI Execution Autonomy</h2>
<p>Automation has long been conceptualized as a continuum that differs in the extent to which control is allocated to the machine rather than to the human operator. Early work described levels of automation in terms of how much authority is transferred from the human to the system. Later work extended this view by distinguishing not only levels of automation but also stages of information processing, showing that automation can support or replace the human at different points in the task cycle. This distinction is important because the consequences of automation depend not only on how much control is delegated but also on which function is being delegated (Sheridan &amp; Verplank, 1978; Parasuraman et al., 2000).</p>
<p>Subsequent research has shown that increasing automation is not simply a matter of reducing human effort. Rather, higher levels of automation change the structure of human involvement. Instead of directly performing each task step, the human increasingly supervises, monitors, and selectively intervenes when necessary. This is particularly relevant for contemporary AI systems, which are no longer limited to presenting information or recommendations but can increasingly generate, select, and implement actions within a workflow. In such settings, greater autonomy may improve efficiency, but it can also create new supervisory demands, such as tracking what the system is doing, understanding its operational state, and recognizing when correction is necessary (Endsley, 2017; Sarter &amp; Woods, 1995; Wickens et al., 2010).</p>
<p>These dynamics are also consistent with broader work on flexible human–automation collaboration. Rather than treating automation as a fixed substitution of machine for human, later approaches have argued that the design challenge lies in how control is delegated, negotiated, and retained across task stages. In supervisory settings, the central issue is therefore not only whether automation exists, but how much execution authority is transferred and how much meaningful control remains available to the user (Miller &amp; Parasuraman, 2003; Miller &amp; Parasuraman, 2007).</p>
<p>Against this background, AI execution autonomy in the present study is defined as the extent to which the system independently determines and executes task-related actions within a workflow. This definition emphasizes execution authority rather than mere recommendation. In the Manual condition, execution authority remains with the user and the system performs only validation. In the Assistance condition, the system generates a suggested solution, but the user retains the ability to modify it. In the Execution condition, the system determines the task configuration directly and the user’s role is reduced to acceptance, rejection, or re-selection. These conditions therefore represent qualitatively different allocations of control and provide a concrete operationalization of execution autonomy for empirical comparison.</p>
</section>
<section id="user-task-performance" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="user-task-performance"><span class="header-section-number">2.2</span> User Task Performance</h2>
<p>User task performance refers to how effectively and efficiently a task is completed within a given human–system arrangement. In automated and semi-automated environments, performance is not solely a property of the user, but of the joint human–automation system. Automation can improve performance by reducing cognitive demands and supporting routine processing, but such benefits depend strongly on the type and degree of automation implemented (Parasuraman et al., 2000; Parasuraman &amp; Wickens, 2008).</p>
<p>At the same time, prior work has shown that the relationship between automation and performance is not uniformly positive. Automation may be used appropriately, misused, underused, or abused, and each of these patterns can shape whether performance actually improves. Thus, increases in system autonomy do not automatically guarantee better outcomes. Performance gains depend on whether the automation is reliable enough, whether the delegated task is suitable for automation, and whether the human remains capable of effective oversight when needed (Parasuraman &amp; Riley, 1997).</p>
<p>Much of the literature has examined the effects of automation through constructs such as trust, reliance, situation awareness, and workload. These constructs are important because they shape how users interact with automation. However, they do not directly capture whether a task was completed quickly, accurately, and successfully. For execution-oriented AI systems, this distinction becomes particularly important because if the system takes over more of the workflow, its value should also be reflected in observable task outcomes, not only in subjective impressions. Trust-centered perspectives show that trust influences reliance on automation, but they do not by themselves provide a full account of concrete task performance in execution contexts (Lee &amp; See, 2004; Hoff &amp; Bashir, 2015; Dzindolet et al., 2003).</p>
<p>For this reason, the present study conceptualizes user task performance in behavioral terms. Three objective indicators are used: completion time, detected errors, and task abandonment. Completion time captures efficiency, that is, how quickly the task is completed. Detected errors capture breakdowns in valid task execution when system constraints are violated. Task abandonment captures unsuccessful task progression, indicating that task initiation did not lead to completion. Together, these measures provide a direct and observable view of task performance under different levels of AI execution autonomy.</p>
</section>
<section id="intervention-behavior" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="intervention-behavior"><span class="header-section-number">2.3</span> Intervention Behavior</h2>
<p>Whereas task performance captures the outcome of interaction, intervention behavior captures the extent to which users step in and modify, override, or reject the system’s actions during task execution. In human–automation interaction, intervention is closely tied to broader issues of monitoring, reliance, trust, and supervisory control. Appropriate reliance on automation often becomes visible in whether users accept automation outputs or choose to intervene, and higher autonomy does not eliminate the human role but often transforms it into one of supervision and recovery when system output is questioned or needs correction (Lee &amp; See, 2004; Endsley, 2017).</p>
<p>Intervention is theoretically important because it reflects how users respond to different allocations of control. A low level of intervention may indicate that the system output was accepted with little need for correction, but it may also reflect a lack of opportunity to intervene. A high level of intervention may indicate preserved user control, reduced confidence in the system, or the need to correct inadequate system outputs. As a result, intervention should not be interpreted as inherently positive or negative; rather, it provides evidence about how the human–AI relationship is enacted during task execution.</p>
<p>This perspective is strengthened by research on automation bias, algorithm aversion, and flexible delegation. Users do not simply accept or reject automation in a uniform way. They may over-rely on automated outputs, avoid automation after observing errors, or become more willing to use automation when they retain even a small degree of adjustment power over system output. These findings suggest that intervention is not only a sign of distrust or failure, but also an indicator of how users regulate control when interacting with semi-autonomous or execution-oriented systems (Mosier &amp; Skitka, 1999; Dietvorst et al., 2015; Dietvorst et al., 2018; Miller &amp; Parasuraman, 2007).</p>
<p>In the present study, intervention behavior is operationalized through system-logged user actions. Specifically, interventions include edits of task parameters (<code>FIELD_EDIT</code>), overrides of system-generated decisions (<code>OVERRIDE</code>), and rejection or regeneration of outputs (<code>AI_SUGGESTION_REJECTED</code>). This allows intervention to be examined both as a binary occurrence and as a quantitative count. In addition, the specific forms of intervention can be distinguished descriptively, making it possible to examine not only whether users intervened, but also how they intervened.</p>
</section>
<section id="research-gap-and-hypotheses" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="research-gap-and-hypotheses"><span class="header-section-number">2.4</span> Research Gap and Hypotheses</h2>
<p>Although human–automation research provides a strong foundation for understanding the distribution of control between people and systems, several limitations remain when this literature is applied to contemporary AI execution contexts. First, much of the established literature has focused on automation broadly defined, often in relation to trust, reliance, workload, and situation awareness rather than on objective, behavior-based outcomes in digital task workflows. Second, a large proportion of prior work has examined assistive or advisory automation, in which the human still retains primary execution authority. As a result, less is known about what happens when AI systems move beyond support and begin to shape or execute task outcomes more directly (Lee &amp; See, 2004; Hoff &amp; Bashir, 2015; Endsley, 2017).</p>
<p>This gap is especially relevant because execution-oriented AI changes the role of the user. When the system not only recommends but also performs workflow-relevant actions, the central design question is no longer simply whether users trust or like the system, but how different levels of execution autonomy affect observable performance and intervention patterns. Existing theories imply that such effects should exist, but they do not yet provide sufficient empirical evidence for behavior-based comparisons in execution-oriented digital workflows. The gap is therefore not only conceptual but also methodological, because objective log-based evidence comparing Manual, Assistance, and Execution conditions remains limited (Parasuraman et al., 2000; Miller &amp; Parasuraman, 2003; Endsley, 2017).</p>
<p>Recent literature also suggests that this gap has become more pressing with the rise of systems that act with greater apparent agency. Research on algorithm aversion and human–automation delegation indicates that user responses to automation are shaped not only by perceived accuracy but also by the degree of retained control and the possibility of correction. This implies that execution autonomy should be studied not only as a technical property of the system, but also as a design condition that reshapes human performance and intervention behavior in measurable ways (Dietvorst et al., 2015; Dietvorst et al., 2018; Miller &amp; Parasuraman, 2007).</p>
<p>To address this gap, the present study examines how different levels of AI execution autonomy affect user task performance and intervention behavior in a controlled digital workflow using system-generated log data. Based on the theoretical expectation that higher execution autonomy can reduce manual effort and alter the need for user intervention, the following hypotheses are proposed:</p>
<p>H1: Higher levels of AI execution autonomy improve user task performance, as reflected in reduced completion time, lower error occurrence, and lower abandonment rates.</p>
<p>H2: Higher levels of AI execution autonomy reduce user intervention during task execution.</p>
</section>
</section>
<section id="methods" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methods</h1>
<section id="study-design" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="study-design"><span class="header-section-number">3.1</span> Study Design</h2>
<p>This study employed a <strong>between-subject experimental design</strong> with three conditions representing different levels of AI execution autonomy: Manual, Assistance, and Execution.</p>
<p>Participants were randomly assigned to one of the three conditions and completed a single task within the assigned condition. The between-subject design was chosen to avoid learning effects and to ensure that user behavior was not influenced by prior exposure to other autonomy levels.</p>
</section>
<section id="prototype-and-logging" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="prototype-and-logging"><span class="header-section-number">3.2</span> Prototype and Logging</h2>
<p>A web-based exam registration system was developed to simulate a realistic academic workflow. The system required users to select a semester, choose an exam period, and configure a valid set of exams under predefined constraints.</p>
<p>User interactions were logged using a backend logging system implemented with Supabase. The logging system captured event-level interaction data, including user actions (e.g., TASK_STARTED, TASK_COMPLETED, ERROR_SHOWN, FIELD_EDIT, OVERRIDE, AI_SUGGESTION_REJECTED), timestamps (client-side and server-side), session identifiers, and the assigned condition (mode). The collected data was stored as structured event logs and exported as CSV files for analysis. This approach enabled a detailed reconstruction of user behavior during task execution.</p>
</section>
<section id="variables" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="variables"><span class="header-section-number">3.3</span> Variables</h2>
<p>The independent variable (IV) in this study was the level of AI execution autonomy, with three levels: Manual, Assistance, and Execution. The dependent variables (DVs) captured objective behavioral outcomes derived from interaction logs: task completion time, error occurrence, task abandonment, and intervention behavior. These variables were operationalized based on observable interaction events.</p>
</section>
<section id="sample" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sample"><span class="header-section-number">3.4</span> Sample</h2>
<p>A total of 231 participants were included in the study. The participant distribution across conditions is shown in Table 1.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1. Number of participants per condition</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">Participants</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">231</td>
</tr>
<tr class="even">
<td style="text-align: left;">Assistance</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution</td>
<td style="text-align: right;">76</td>
</tr>
<tr class="even">
<td style="text-align: left;">Information</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">manual</td>
<td style="text-align: right;">76</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>An important issue in the dataset is the presence of the “Information” mode, which theoretically should not exist as an active interaction condition. Therefore, it is necessary to investigate why this mode appears in the logs and what type of events have been recorded under it. To assess this, a validity check was conducted by filtering all entries associated with the “Information” mode and inspecting their session IDs and logged actions.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2. Log entries recorded under the Information condition.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Session ID</th>
<th style="text-align: left;">Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S-7QR92FMR</td>
<td style="text-align: left;">PAGE_VIEW</td>
</tr>
<tr class="even">
<td style="text-align: left;">S-KY2JLRYQ</td>
<td style="text-align: left;">PAGE_VIEW</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S-NT977W23</td>
<td style="text-align: left;">PAGE_VIEW</td>
</tr>
<tr class="even">
<td style="text-align: left;">S-OQKZ8TJ1</td>
<td style="text-align: left;">PAGE_VIEW</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The inspection showed that the “Information” mode contained only four log entries, all of which were recorded as <code>PAGE_VIEW</code> events. This indicates that these entries reflect passive page access rather than meaningful task-related interaction. Therefore, the “Information” mode was treated as invalid and excluded from further analysis to ensure data quality, cleanliness and consistency.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3. Number of participants after data cleaning (excluding Information condition)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">Participants</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">227</td>
</tr>
<tr class="even">
<td style="text-align: left;">Assistance</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution</td>
<td style="text-align: right;">76</td>
</tr>
<tr class="even">
<td style="text-align: left;">manual</td>
<td style="text-align: right;">76</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Repeated participation was intended to be prevented by the system design. However, to ensure data validity, an additional check was conducted at the session level, since repeated participation may still occur despite implemented controls in the experimental environment. Therefore, sessions were used to verify that each participant contributed only one observation and to avoid overcounting repeated entries.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 4. Number of unique sessions (one per participant) per condition</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">Sessions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Assistance</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Execution</td>
<td style="text-align: right;">76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">manual</td>
<td style="text-align: right;">76</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The results show a balanced distribution of unique sessions across conditions, indicating that each participant contributed only one observation and that no overcounting occurred.</p>
</section>
<section id="measures" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="measures"><span class="header-section-number">3.5</span> Measures</h2>
<p>All dependent variables were derived from system-generated event logs and aggregated at the session level.</p>
<p>Task completion time was defined as the time interval between task start and task completion within a session. Specifically, it reflects the elapsed time between the first <code>TASK_STARTED</code> event and the corresponding <code>TASK_COMPLETED</code> event. As this measure requires a valid endpoint, it was calculated only for sessions that were completed successfully.</p>
<p>To complement this efficiency-based measure, task abandonment was included as an indicator of unsuccessful task progression. Task abandonment was defined as sessions in which users initiated but did not complete the task. Thus, a session was classified as abandoned when a <code>TASK_STARTED</code> event was recorded without a corresponding <code>TASK_COMPLETED</code> event. Figure 1 provides an overview of overall task progression across all 224 participants. It shows the number of participants who entered the system but did not start the task, those who started the task but did not complete it, and those who started and successfully completed the task.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-task-progress-overall" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-task-progress-overall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-task-progress-overall-1.png" class="img-fluid figure-img" width="528">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-task-progress-overall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Overall task progression across all participants.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Building on this general overview, Figure 1 first showed overall task progression across the full sample and indicated that 64 participants did not start the task at all. The following analysis therefore focuses only on the 160 participants who initiated the task. Among these started sessions, the aim is to examine how task outcomes were distributed across the three autonomy conditions by distinguishing between participants who started but did not complete the task and those who started and successfully completed it. To display these condition-specific differences more clearly, a grouped bar chart was used in Figure 2.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-task-outcome-by-mode" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-task-outcome-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-task-outcome-by-mode-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-task-outcome-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Distribution of completed and abandoned task outcomes among started sessions across the three autonomy conditions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 2 shows the distribution of task outcomes among participants who started the task, separated by autonomy condition. Across all three conditions, completed sessions outnumbered abandoned sessions. The Execution condition showed the highest number of completed sessions and the lowest number of abandoned sessions, whereas the manual condition showed the highest number of abandoned sessions.</p>
<p>Error occurrence was operationalized through ERROR_SHOWN events. Sessions were included in this analysis if a task had been started, regardless of whether the task was later completed or abandoned. This approach ensured that validation problems encountered during task execution were captured independently of final task outcome. Abandoned sessions were retained in the analysis because errors themselves may have contributed to task abandonment. We further examined whether error occurrence differed between completed and abandoned sessions. As shown in Figure 3, a 100% stacked bar chart was used to compare the proportion of sessions with and without errors across the two task outcomes. This visualization makes it possible to assess what percentage of completed sessions contained at least one error and what percentage of abandoned sessions contained at least one error.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-error-by-outcome" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-error-by-outcome-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-error-by-outcome-1.png" class="img-fluid figure-img" width="528">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-error-by-outcome-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Error occurrence in completed and abandoned sessions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 3 shows the proportion of sessions with and without errors across completed and abandoned started sessions. A higher proportion of abandoned sessions contained at least one error (37%) compared with completed sessions (28%). This pattern suggests that validation errors may have contributed to task abandonment, although no causal conclusion can be drawn from this descriptive comparison alone. To further refine this analysis, error occurrence was examined separately for each autonomy condition. This makes it possible to compare how the proportion of sessions with and without errors differed between completed and abandoned sessions within the Manual, Assistance, and Execution conditions.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-error-by-outcome-mode" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-error-by-outcome-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-error-by-outcome-mode-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-error-by-outcome-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Proportion of sessions with and without errors in completed and abandoned sessions across autonomy conditions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 4 shows that error occurrence varied substantially across autonomy conditions. The Manual condition displayed the highest proportion of sessions with errors in both completed and abandoned sessions, whereas the Execution condition showed the lowest error proportions overall. The Assistance condition fell between these two extremes. At the same time, the relationship between error occurrence and task outcome was not uniform across conditions, suggesting that the role of validation errors may differ depending on the level of AI execution autonomy.</p>
<p>Intervention behavior was operationalized as active user interference with the task configuration or the system output. At the session level, intervention was defined based on the occurrence of FIELD_EDIT, OVERRIDE, and AI_SUGGESTION_REJECTED events. For the following descriptive overview, a binary intervention indicator was used to distinguish between sessions with at least one intervention and sessions without any intervention. Only started sessions were included in this analysis, regardless of whether the task was later completed or abandoned. Intervention should be measured for all started sessions, because it reflects user behavior during task execution rather than successful task completion. Figure 5 shows the proportion of sessions with and without intervention across the three autonomy conditions.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-intervention-by-mode" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-intervention-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-intervention-by-mode-1.png" class="img-fluid figure-img" width="595">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-intervention-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Proportion of sessions with and without intervention across autonomy conditions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 5 shows that intervention occurred in the large majority of started sessions across all three autonomy conditions. The proportion of sessions with at least one intervention was consistently high in the Manual, Assistance, and Execution conditions, indicating that user intervention was common regardless of autonomy level. At the descriptive level, only minor differences between conditions were observed.</p>
<p>This pattern may indicate that the binary intervention measure captured a very broad range of user actions, thereby limiting its ability to differentiate more clearly between autonomy conditions. Alternatively, it may suggest that intervention was generally required across conditions due to the structure of the task. These interpretations are considered in the discussion.</p>
<p>Figure 6 provides a more fine-grained view of intervention behavior by showing the distribution of intervention counts across the three autonomy conditions. In contrast to the binary intervention indicator used in Figure 5, this analysis captures how often users intervened within a session. Only started sessions were included, as intervention could only occur once task execution had begun.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-intervention-count-by-mode" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-intervention-count-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-intervention-count-by-mode-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-intervention-count-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Distribution of intervention counts across autonomy conditions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 6 suggests that intervention frequency differed across autonomy conditions. The Manual condition showed the highest intervention counts overall, whereas the Execution condition showed the lowest. The Assistance condition fell between these two extremes. This descriptive pattern is consistent with the expectation that greater execution autonomy reduces the need for user intervention, although formal statistical testing is required to assess whether these differences are significant.</p>
</section>
<section id="data-preparation-and-analysis" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="data-preparation-and-analysis"><span class="header-section-number">3.6</span> Data Preparation and Analysis</h2>
<p>The raw dataset consisted of event-level interaction logs. Prior to analysis, all entries associated with the <code>Information</code> mode were excluded because they reflected passive <code>PAGE_VIEW</code> events rather than meaningful task-related interaction. In addition, repeated participation was checked at the participant-session level, and no repeated entries were identified. After this cleaning step, the data were aggregated to the session level, so that each session represented one participant’s interaction within one assigned condition.</p>
<p>Based on this session-level aggregation, summary variables were derived for task progress, task completion, abandonment, error occurrence, and intervention behavior. Sessions in which the task was not started were retained for the descriptive overview of overall task progression, but they were excluded from analyses that required actual task execution. Accordingly, abandonment, error occurrence, and intervention behavior were analyzed only for started sessions. Task completion time was calculated only for completed sessions, as this measure required both a valid start point and a valid end point.</p>
<p>Statistical analyses will be conducted according to the measurement level of the respective variables. As task completion time represents a continuous outcome across three autonomy conditions, differences will be examined using a non-parametric Kruskal–Wallis test, followed by pairwise Wilcoxon rank-sum tests where appropriate. Abandonment, error occurrence, and intervention occurrence will be analyzed as categorical outcomes using chi-square and proportion-based tests.</p>
</section>
</section>
<section id="results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<p>This section reports the empirical results in relation to the two hypotheses of the study. First, the effects of AI execution autonomy on task performance are examined, including completion time, detected errors, and task completion versus abandonment. Second, the effects on intervention behavior are presented, covering intervention occurrence, intervention frequency, and the different types of intervention observed across conditions.</p>
<section id="h1-task-performance" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="h1-task-performance"><span class="header-section-number">4.1</span> H1: Task Performance</h2>
<p>To evaluate H1, task performance was examined across the three autonomy conditions using three outcome dimensions: completion time, detected errors, and task completion versus abandonment. Together, these measures provide an overview of how efficiently and successfully participants performed the task under different levels of AI execution autonomy.</p>
<section id="completion-time" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="completion-time"><span class="header-section-number">4.1.1</span> Completion Time</h3>
<p>Task completion time was operationalized as the elapsed time between the beginning and the successful completion of task execution within a session. For this measure, TASK_STARTED was treated as the starting point of task execution, and TASK_COMPLETED was treated as the endpoint indicating successful task completion. Because the analysis focused on elapsed interaction time within the system, completion time was calculated using the client-side timestamp variable (client_ts_ms). This timestamp was used because it directly reflects the temporal order and duration of user interactions during task execution. Accordingly, completion time was defined only for sessions in which both a valid task start and a valid task completion event were recorded.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 5. Descriptive summary of completion time (in seconds) across autonomy conditions.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">manual</td>
<td style="text-align: right;">36.07</td>
<td style="text-align: right;">27.42</td>
<td style="text-align: right;">12.77</td>
<td style="text-align: right;">100.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">Assistance</td>
<td style="text-align: right;">26.08</td>
<td style="text-align: right;">18.44</td>
<td style="text-align: right;">6.99</td>
<td style="text-align: right;">95.84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution</td>
<td style="text-align: right;">84.82</td>
<td style="text-align: right;">11.82</td>
<td style="text-align: right;">5.34</td>
<td style="text-align: right;">2964.74</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Initial descriptive inspection of completion time suggested substantial skewness, particularly due to very large values in the Execution condition. Therefore, extreme cases were examined before proceeding to inferential analysis. Specifically, the longest completion times were reviewed, and the number of sessions exceeding predefined thresholds was inspected in order to determine whether unusually large values reflected meaningful observations or extreme cases that might distort subsequent comparison.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 10 longest completion times</caption>
<thead>
<tr class="header">
<th style="text-align: left;">session_id</th>
<th style="text-align: left;">mode</th>
<th style="text-align: right;">completion_time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S-E1WBD47E</td>
<td style="text-align: left;">Execution</td>
<td style="text-align: right;">2964.736</td>
</tr>
<tr class="even">
<td style="text-align: left;">S-21WAOP00</td>
<td style="text-align: left;">manual</td>
<td style="text-align: right;">100.968</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S-F5OFN5A6</td>
<td style="text-align: left;">Assistance</td>
<td style="text-align: right;">95.845</td>
</tr>
<tr class="even">
<td style="text-align: left;">S-O1IMAN9C</td>
<td style="text-align: left;">manual</td>
<td style="text-align: right;">94.098</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S-ZWN4PELR</td>
<td style="text-align: left;">manual</td>
<td style="text-align: right;">89.414</td>
</tr>
<tr class="even">
<td style="text-align: left;">S-FRQ1PFYO</td>
<td style="text-align: left;">Assistance</td>
<td style="text-align: right;">84.200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S-7HPZY5JW</td>
<td style="text-align: left;">Assistance</td>
<td style="text-align: right;">67.739</td>
</tr>
<tr class="even">
<td style="text-align: left;">S-HXUZS215</td>
<td style="text-align: left;">Execution</td>
<td style="text-align: right;">67.577</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S-8A4U6AVO</td>
<td style="text-align: left;">Assistance</td>
<td style="text-align: right;">66.537</td>
</tr>
<tr class="even">
<td style="text-align: left;">S-4GNOB2GI</td>
<td style="text-align: left;">manual</td>
<td style="text-align: right;">55.040</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Check of extreme completion times</caption>
<thead>
<tr class="header">
<th style="text-align: right;">total_completed_sessions</th>
<th style="text-align: right;">above_300_sec</th>
<th style="text-align: right;">above_600_sec</th>
<th style="text-align: right;">max_time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">109</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2964.736</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The inspection showed that only one completed session exceeded 300 seconds, with a completion time of approximately 2965 seconds. Because this value was substantially larger than all other observations and strongly distorted the overall distribution, it was treated as an extreme outlier and excluded from the completion-time analysis. All remaining completed sessions were retained for the subsequent descriptive and inferential analyses.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 6. Descriptive summary of completion time (in seconds) across autonomy conditions after exclusion of one extreme outlier.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">manual</td>
<td style="text-align: right;">36.07</td>
<td style="text-align: right;">27.42</td>
<td style="text-align: right;">12.77</td>
<td style="text-align: right;">100.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">Assistance</td>
<td style="text-align: right;">26.08</td>
<td style="text-align: right;">18.44</td>
<td style="text-align: right;">6.99</td>
<td style="text-align: right;">95.84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution</td>
<td style="text-align: right;">17.84</td>
<td style="text-align: right;">10.79</td>
<td style="text-align: right;">5.34</td>
<td style="text-align: right;">67.58</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-completion-time-by-mode-clean" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-completion-time-by-mode-clean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-completion-time-by-mode-clean-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-completion-time-by-mode-clean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Distribution of task completion time across autonomy conditions after exclusion of one extreme outlier.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 7 shows the distribution of task completion time across autonomy conditions after exclusion of one extreme outlier. Descriptively, completion time decreased gradually across the three conditions. Median completion time was highest in the Manual condition (27.42 s), followed by the Assistance condition (18.44 s), and lowest in the Execution condition (10.79 s). Mean completion times showed the same ordering, although they were consistently higher than the medians, indicating a slightly right-skewed distribution. Because completion time was compared across three autonomy conditions and the distribution remained slightly right-skewed, a non-parametric Kruskal–Wallis test was used to examine whether completion time differed significantly between conditions. To complement significance testing, an effect size estimate was also calculated for the Kruskal–Wallis result.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Kruskal–Wallis test for completion time across autonomy conditions.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Statistic</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">21.506</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Effect size (epsilon-squared) for the Kruskal–Wallis test on completion time.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">ε²</th>
<th style="text-align: center;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.186</td>
<td style="text-align: center;">relatively large</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A Kruskal–Wallis test revealed a statistically significant overall difference in completion time across the three autonomy conditions, H(2) = 21.51, p &lt; .001, ε² = .186. Thus, the level of AI execution autonomy was significantly associated with variation in task completion time, and the observed effect was comparatively substantial.</p>
<p>Because the Kruskal–Wallis test revealed a significant overall difference in completion time across autonomy conditions, post-hoc pairwise comparisons were performed to determine which specific condition pairs differed significantly. Pairwise Wilcoxon rank-sum tests with Bonferroni correction were used for this purpose.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Pairwise Wilcoxon post-hoc comparisons for completion time.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Assistance vs manual</td>
<td style="text-align: left;">0.0136</td>
</tr>
<tr class="even">
<td style="text-align: left;">Execution vs manual</td>
<td style="text-align: left;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution vs Assistance</td>
<td style="text-align: left;">0.0367</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Post-hoc pairwise Wilcoxon comparisons showed that all pairwise comparisons were statistically significant. Completion time was significantly lower in the Assistance condition than in the Manual condition (p = .014), significantly lower in the Execution condition than in the Manual condition (p &lt; .001), and significantly lower in the Execution condition than in the Assistance condition (p = .037). These results indicate a stepwise reduction in completion time as AI execution autonomy increased.</p>
</section>
<section id="detected-errors" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="detected-errors"><span class="header-section-number">4.1.2</span> Detected Errors</h3>
<p>Detected errors were operationalized based on <code>ERROR_SHOWN</code> events. For the present analysis, all sessions in which the task had been started were included, regardless of whether the task was later completed or abandoned. At the session level, error occurrence was treated as a binary outcome indicating whether at least one validation error was recorded during task execution.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-error-by-mode" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-error-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-error-by-mode-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-error-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Proportion of started sessions with and without detected errors across autonomy conditions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 8 shows the proportion of started sessions with and without at least one detected error across the three autonomy conditions. Descriptively, the Manual condition showed the highest proportion of sessions with at least one detected error, whereas the Assistance and Execution conditions showed substantially lower proportions.</p>
<p>To examine whether detected error occurrence differed across autonomy conditions, a chi-square test of independence was conducted. Because error occurrence was defined as a binary categorical session-level outcome, this test was appropriate for assessing differences in the distribution of error presence across conditions. To complement significance testing, Cramér’s V was calculated as an effect size estimate for the chi-square result.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Chi-square test for detected errors across autonomy conditions.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Statistic</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">25.525</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Effect size (Cramér’s V) for the chi-square test on detected errors.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Cramér’s V</th>
<th style="text-align: center;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.399</td>
<td style="text-align: center;">medium</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A chi-square test revealed a statistically significant association between autonomy condition and detected error occurrence, χ²(2) = 25.53, p &lt; .001, Cramér’s V = 0.40, indicating a medium effect size. Because the overall test was significant, post-hoc pairwise proportion tests with Bonferroni adjustment were conducted to identify which specific condition pairs differed.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Pairwise proportion tests for detected errors.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Assistance vs manual</td>
<td style="text-align: left;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Execution vs manual</td>
<td style="text-align: left;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution vs Assistance</td>
<td style="text-align: left;">1.000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Pairwise comparisons showed that the Manual condition differed significantly from both the Assistance condition (p &lt; .001) and the Execution condition (p &lt; .001), whereas no statistically significant difference was found between the Assistance and Execution conditions (p = 1.00). The proportion of started sessions with at least one detected error thus decreased from Manual to both system-supported conditions, but this reduction was statistically significant only when comparing Manual with the other two conditions.</p>
</section>
<section id="task-completion-and-abandonment" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="task-completion-and-abandonment"><span class="header-section-number">4.1.3</span> Task Completion and Abandonment</h3>
<p>Task completion and abandonment were examined as mutually exclusive outcomes among started sessions. At the session level, a task was classified as completed when a <code>TASK_COMPLETED</code> event was recorded after task initiation. A task was classified as abandoned when a <code>TASK_STARTED</code> event was present but no corresponding <code>TASK_COMPLETED</code> event was recorded.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-abandonment-by-mode" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-abandonment-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-abandonment-by-mode-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-abandonment-by-mode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Proportion of completed and abandoned started sessions across autonomy conditions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 9 shows the proportion of completed and abandoned sessions among participants who started the task. Descriptively, the Manual condition showed the highest proportion of abandoned sessions (45%), the Assistance condition fell in between (33%), and the Execution condition showed the lowest proportion of abandonment (17%). To examine whether task outcome differed significantly across autonomy conditions, a chi-square test of independence was conducted. Because task completion versus abandonment was treated as a categorical session-level outcome, this test was appropriate for assessing differences in the distribution of task outcomes across conditions. All expected cell frequencies exceeded 5, satisfying the assumption required for the chi-square approximation to be valid. To complement significance testing, Cramér’s V was calculated as an effect size estimate.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Chi-square test for task completion versus abandonment across autonomy conditions.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Statistic</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">9.855</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.007</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Effect size (Cramér’s V) for the chi-square test on task completion versus abandonment.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Cramér’s V</th>
<th style="text-align: center;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.248</td>
<td style="text-align: center;">small</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Because the chi-square test indicated an overall difference across autonomy conditions, additional pairwise proportion tests were conducted to determine which specific pairs of conditions differed in task abandonment. Bonferroni adjustment was applied to control for multiple comparisons.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Pairwise proportion tests for task abandonment.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Assistance vs manual</td>
<td style="text-align: left;">0.857</td>
</tr>
<tr class="even">
<td style="text-align: left;">Execution vs manual</td>
<td style="text-align: left;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution vs Assistance</td>
<td style="text-align: left;">0.254</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>To further quantify the magnitude of differences between conditions, odds ratios with 95% confidence intervals were computed for each pairwise comparison.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Odds ratios with 95% confidence intervals for pairwise comparisons of task abandonment.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: center;">Odds Ratio</th>
<th style="text-align: center;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">manual vs Assistance</td>
<td style="text-align: center;">1.66</td>
<td style="text-align: center;">[0.76, 3.62]</td>
</tr>
<tr class="even">
<td style="text-align: left;">manual vs Execution</td>
<td style="text-align: center;">4.05</td>
<td style="text-align: center;">[1.65, 9.93]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Assistance vs Execution</td>
<td style="text-align: center;">2.44</td>
<td style="text-align: center;">[0.98, 6.09]</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The chi-square test showed that task outcome differed significantly across autonomy conditions, χ²(2) = 9.86, p = .007, Cramér’s V = 0.25. Post-hoc pairwise proportion tests showed that the Execution condition differed significantly from the Manual condition (p = .010). The corresponding odds ratio indicated that the odds of task abandonment in the Manual condition were approximately four times higher than in the Execution condition (OR = 4.05, 95% CI [1.65, 9.93]). No significant differences were found between the Assistance and Manual conditions (p = .857; OR = 1.66, 95% CI [0.76, 3.62]) or between the Execution and Assistance conditions (p = .254; OR = 2.44, 95% CI [0.98, 6.09]), though the latter comparison was numerically notable with a CI that narrowly included 1. Overall, these results suggest that higher AI execution autonomy was associated with substantially reduced task abandonment, most clearly when comparing the Execution condition to the Manual condition.</p>
</section>
</section>
<section id="h2-intervention-behavior" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="h2-intervention-behavior"><span class="header-section-number">4.2</span> H2: Intervention Behavior</h2>
<p>To evaluate H2, intervention behavior was examined across the three autonomy conditions using three complementary indicators: intervention occurrence, intervention count, and the specific types of intervention observed during task execution. Together, these measures provide a more detailed picture of how strongly users interfered with the system under different levels of AI execution autonomy.</p>
<section id="intervention-occurrence" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="intervention-occurrence"><span class="header-section-number">4.2.1</span> Intervention Occurrence</h3>
<p>Intervention occurrence was operationalized as a binary session-level outcome indicating whether at least one intervention took place during task execution. A session was classified as involving intervention if at least one <code>FIELD_EDIT</code>, <code>OVERRIDE</code>, or <code>AI_SUGGESTION_REJECTED</code> event was recorded. Only started sessions were included in this analysis, regardless of whether the task was later completed or abandoned.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-intervention-occurrence-h2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-intervention-occurrence-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-intervention-occurrence-h2-1.png" class="img-fluid figure-img" width="595">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-intervention-occurrence-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Proportion of started sessions with and without intervention across autonomy conditions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 10 shows the proportion of started sessions with and without intervention across the three autonomy conditions. Descriptively, intervention occurred in the large majority of started sessions in all three conditions. The proportions were very similar across Manual (92%), Assistance (94%), and Execution (91%), indicating only minor descriptive differences in intervention occurrence between autonomy conditions. To examine whether intervention occurrence differed significantly across autonomy conditions, a chi-square test of independence was conducted. Because intervention occurrence was treated as a categorical session-level outcome, this test was appropriate for assessing differences in the distribution of intervention presence across conditions. All expected cell frequencies exceeded 5, satisfying the assumption required for the chi-square approximation to be valid. To complement significance testing, Cramér’s V was calculated as an effect size estimate.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Chi-square test for intervention occurrence across autonomy conditions.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Statistic</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.58</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.748</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Effect size (Cramér’s V) for the chi-square test on intervention occurrence.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Cramér’s V</th>
<th style="text-align: center;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">small</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The chi-square test showed that intervention occurrence did not differ significantly across autonomy conditions, χ²(2) = 0.58, p = .748, Cramér’s V = 0.06. This indicates that the proportion of started sessions containing at least one intervention was similarly high across the Manual, Assistance, and Execution conditions. Overall, these results suggest that intervention occurrence, as a binary measure, did not clearly distinguish between levels of AI execution autonomy.</p>
</section>
<section id="intervention-count" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="intervention-count"><span class="header-section-number">4.2.2</span> Intervention Count</h3>
<p>In addition to intervention occurrence, intervention count was examined to capture how often users intervened within a session. At the session level, intervention count was calculated as the sum of <code>FIELD_EDIT</code>, <code>OVERRIDE</code>, and <code>AI_SUGGESTION_REJECTED</code> events. Only started sessions were included, as intervention could only occur once task execution had begun.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-intervention-count-h2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-intervention-count-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-intervention-count-h2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-intervention-count-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Distribution of intervention counts across autonomy conditions.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Descriptive statistics for intervention count per autonomy condition.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: center;">n</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">IQR</th>
<th style="text-align: center;">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">manual</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Assistance</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">5.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Descriptively, Figure 11 and the descriptive statistics below suggest that intervention count differed across autonomy conditions. The Manual condition showed the highest median intervention count (Mdn = 7, IQR = 6), while both the Assistance and Execution conditions showed substantially lower medians (Mdn = 3 for both). Although the medians were equal for Assistance and Execution, the Execution condition displayed notably less spread (IQR = 0 vs.&nbsp;IQR = 3) and a lower mean (4.2 vs.&nbsp;5.1), indicating that intervention frequency was not only lower but also more consistent in the Execution condition. The Manual condition also displayed the greatest spread, indicating that intervention frequency was both higher and more variable under fully manual operation.</p>
<p>Because intervention count represents a count-based session-level outcome and the distribution was visibly non-normal, a non-parametric Kruskal–Wallis test was conducted to examine whether intervention count differed significantly across autonomy conditions.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Kruskal–Wallis test for intervention count across autonomy conditions.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Statistic</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">26.693</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Effect size (epsilon-squared) for the Kruskal–Wallis test on intervention count.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">ε²</th>
<th style="text-align: center;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.157</td>
<td style="text-align: center;">large</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A Kruskal–Wallis test showed that intervention count differed significantly across autonomy conditions, H(2) = 26.69, p &lt; .001, ε² = .157. The effect size indicates a large association between autonomy condition and intervention frequency. Because the Kruskal–Wallis test indicated an overall difference in intervention count across conditions, additional post-hoc pairwise Wilcoxon rank-sum tests were conducted. Bonferroni adjustment was applied to control for multiple comparisons.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Pairwise Wilcoxon post-hoc comparisons for intervention count with rank-biserial correlation.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: center;">p-value</th>
<th style="text-align: center;">r (rank-biserial)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Assistance vs manual</td>
<td style="text-align: center;">&lt; .001</td>
<td style="text-align: center;">-0.415</td>
</tr>
<tr class="even">
<td style="text-align: left;">Execution vs manual</td>
<td style="text-align: center;">&lt; .001</td>
<td style="text-align: center;">-0.546</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution vs Assistance</td>
<td style="text-align: center;">1.000</td>
<td style="text-align: center;">-0.098</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Post-hoc pairwise Wilcoxon comparisons showed that intervention count was significantly lower in the Assistance condition than in the Manual condition (p &lt; .001, r = −0.42) and significantly lower in the Execution condition than in the Manual condition (p &lt; .001, r = −0.55), indicating medium-to-large effects. No significant difference was found between the Assistance and Execution conditions (p = 1.00, r = −0.10). Overall, these results indicate that higher AI execution autonomy was associated with a substantially lower frequency of user intervention compared with the Manual condition, although the difference between Assistance and Execution was not statistically significant.</p>
</section>
<section id="types-of-intervention" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="types-of-intervention"><span class="header-section-number">4.2.3</span> Types of Intervention</h3>
<p>To further differentiate intervention behavior, the specific types of intervention were examined separately. Three event categories were considered: <code>FIELD_EDIT</code>, <code>OVERRIDE</code>, and <code>AI_SUGGESTION_REJECTED</code>. Because the binary occurrence of each intervention type was expected to vary markedly across conditions, chi-square or Fisher’s exact tests were applied where assumptions permitted. Edit occurrence approached ceiling (&gt;90% in all conditions), which precluded reliable statistical testing due to low expected cell counts in the “no edit” category; it was therefore examined descriptively only. Override and Reject occurrence were tested formally using Fisher’s exact test, which was preferred over chi-square because some observed cell counts were zero.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-intervention-types-h2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-intervention-types-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ai-execution-autonomy-analysis_files/figure-html/fig-intervention-types-h2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-intervention-types-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Proportion of started sessions containing each intervention type across autonomy conditions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 12 shows the proportion of started sessions containing each intervention type across the three autonomy conditions. Edits were highly prevalent in all three conditions, occurring in more than 90% of started sessions across all conditions (Manual: 92%, Assistance: 94%, Execution: 91%). In contrast, override events occurred only in the Assistance (81%) and Execution (91%) conditions and were entirely absent in the Manual condition. Rejection-related intervention was observed only in the Assistance condition (35%) and was absent in both the Manual and Execution conditions.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Fisher’s exact tests for Override and Reject intervention type occurrence across autonomy conditions.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Intervention Type</th>
<th style="text-align: center;">Fisher’s p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Override</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Reject</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Fisher’s exact tests confirmed that both Override and Reject occurrence differed significantly across autonomy conditions (both p &lt; .001). The pattern for Override reflects the nature of the system-supported conditions: because the system generates suggestions in the Assistance and Execution conditions, users in those conditions have the opportunity to override AI output — an action that is structurally impossible in the Manual condition. The pattern for Reject, concentrated exclusively in the Assistance condition, suggests that users in that condition actively declined AI suggestions more often than those in the Execution condition, possibly reflecting a greater sense of perceived control or a less obligatory acceptance dynamic. Edit occurrence was not formally tested due to near-ceiling proportions in all conditions, which would have violated the expected cell count assumption.</p>
<p>Taken together, the results provide partial support for H2. While intervention occurrence did not differ significantly across autonomy conditions, intervention count showed that users in the Manual condition intervened significantly more often than users in the Assistance and Execution conditions. The descriptive analysis of intervention types further showed that intervention was not uniform across conditions: edits were common in all three conditions, whereas overrides and rejection-related actions were concentrated in the system-supported conditions. Overall, these findings suggest that higher AI execution autonomy did not eliminate intervention altogether, but it reduced how frequently users needed to intervene and changed the form that intervention took.</p>
</section>
</section>
</section>
<section id="discussion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion</h1>
<section id="evaluation-of-hypotheses" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="evaluation-of-hypotheses"><span class="header-section-number">5.1</span> Evaluation of Hypotheses</h2>
<p>The present study examined how AI execution autonomy shapes user task performance and intervention behavior across three operationally distinct conditions: Manual, Assistance, and Execution. The findings provide differentiated support for both hypotheses, with the most consistent effects emerging in comparisons between the Manual condition and the two system-supported conditions.</p>
<p>H1 was largely supported. Higher AI execution autonomy was associated with improved performance across all three indicators, though the pattern was not uniform across measures. Completion time decreased in a statistically significant stepwise gradient — from Manual to Assistance to Execution — indicating that each incremental transfer of execution authority produced a measurable reduction in task duration. For detected errors and task abandonment, improvement followed a less finely graded pattern: both system-supported conditions showed significantly lower error proportions than the Manual condition but did not differ significantly from each other; for abandonment, the statistically significant overall effect was driven primarily by the contrast between the Manual and Execution conditions. H1 is therefore supported across all performance indicators, while the linearity of improvement holds most clearly for completion time.</p>
<p>H2 received only partial support. Intervention occurrence — whether any intervention took place within a started session — did not differ significantly across conditions, remaining near ceiling in all three. Intervention count, by contrast, showed a significant effect: participants in the Manual condition intervened substantially more frequently than those in either system-supported condition, while Assistance and Execution did not differ from each other on this measure. Descriptive analysis of intervention types revealed a qualitative shift: field edits predominated across all conditions, whereas override and rejection actions were structurally confined to the system-supported conditions, as confirmed by Fisher’s exact tests (both <em>p</em> &lt; .001). H2 is therefore supported with respect to the frequency of intervention, but the null result for intervention occurrence establishes that higher autonomy does not reduce the probability of any user engagement — only its intensity and character.</p>
</section>
<section id="interpretation" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">5.2</span> Interpretation</h2>
<p>The performance advantages observed across the system-supported conditions are consistent with the theoretical expectation that delegating execution authority to a well-specified system reduces the manual burden of completing a constrained, rule-governed task (Parasuraman et al., 2000; Parasuraman &amp; Wickens, 2008). In the present study, both system-supported conditions relieved users of the need to construct a valid exam configuration through iterative parameter adjustment — a process that, in the Manual condition, required sequential decision-making under multiple simultaneous constraints. The system’s ability to generate compliant outputs directly appears to have reduced not only the time required for task completion but also the number of opportunities for constraint violations to accumulate during the configuration process.</p>
<p>The pronounced monotonic effect on completion time — the only outcome to differentiate all three conditions in pairwise comparisons — suggests that execution autonomy was particularly effective at compressing the configuration cycle. From a resource allocation perspective, this is expected: in constraint-governed environments, a system capable of generating a valid solution in a single step short-circuits the iterative decision process that users in the Manual condition executed manually, yielding efficiency gains that scale with the number of sequential decisions bypassed (Parasuraman &amp; Wickens, 2008; Wickens et al., 2010).</p>
<p>A finding of considerable theoretical significance is the limited differentiation between the Assistance and Execution conditions across most outcomes. Despite representing structurally distinct allocations of execution authority — one presenting a modifiable suggestion for user review before confirmation, the other implementing a configuration without requiring prior approval — the two conditions produced broadly comparable behavioral profiles on errors, abandonment, and intervention count. This asymmetry between the Manual-to-Assistance transition and the Assistance-to-Execution transition suggests diminishing marginal returns to execution autonomy: the most consequential design boundary lies at the onset of meaningful system involvement rather than at its upper limit. This pattern resonates with evidence from algorithm adjustability research, which shows that user behavior can shift substantially when even limited modifiability is introduced, while the incremental effect of increasing automation from adjustable to fully fixed tends to be comparatively modest (Dietvorst et al., 2018). It also aligns with flexible automation frameworks that identify the critical design question not as how autonomous to make the system, but as how to structure the onset and form of system involvement to preserve appropriate human oversight (Miller &amp; Parasuraman, 2007).</p>
<p>The null result for intervention occurrence warrants explicit theoretical attention, as it represents an outcome not fully anticipated by a simple autonomy-reduces-intervention model. The near-ceiling proportions across all three conditions reflect the structural properties of the task: because a single field edit sufficed for classification as an intervening session and all conditions retained accessible interface elements, the binary measure was insufficiently sensitive to the autonomy manipulation. The significant effect for intervention count — but not occurrence — illustrates a methodological point of broader relevance: in the presence of near-ceiling binary measures, count-based and type-based decompositions are necessary to detect autonomy effects on user engagement. Treating intervention as a categorical event misrepresents what is, empirically, a distributional phenomenon shaped by task structure, interface affordances, and system behavior simultaneously.</p>
<p>The most theoretically revealing aspect of the results is the qualitative shift in intervention type across autonomy conditions. The structural confinement of override and rejection actions to the system-supported conditions — types of intervention that presuppose the existence of a prior system-generated output — documents a transformation in the human role: from active configurator to evaluative supervisor. This transition directly instantiates the supervisory control dynamic described by Sheridan and Verplank (1978) and elaborated by Endsley (2017), in which increasing system autonomy shifts the human task from primary execution toward monitoring, evaluation, and selective correction. The persistence of field edits at rates exceeding 90% of started sessions across all conditions further indicates that some residual degree of user agency was structurally embedded in the workflow design and was not abolished even at the highest autonomy level tested. This aligns with Bainbridge’s (1983) observation that automation characteristically transforms rather than eliminates human activity: tasks previously performed through direct manipulation become tasks of oversight, validation, and exception handling. In the present study, this transformation is empirically visible not as an absence of user action under higher autonomy, but as a reconfiguration of action type — a shift that any analysis restricted to the binary occurrence of intervention would entirely fail to detect.</p>
</section>
<section id="theoretical-contributions" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="theoretical-contributions"><span class="header-section-number">5.3</span> Theoretical Contributions</h2>
<p>The findings extend human–automation interaction theory in two substantive directions. First, they provide behavioral evidence for the consequences of execution-oriented AI that complements the predominance of advisory and decision-support automation in existing empirical work. Prior research has established extensively that automation affects trust, situation awareness, reliance, and workload, but these outcomes have been assessed predominantly through self-report instruments and under conditions in which humans retain final execution authority (Lee &amp; See, 2004; Parasuraman &amp; Riley, 1997; Hoff &amp; Bashir, 2015). The present study demonstrates that when AI systems assume the authority to implement workflow actions directly, the effects are observable in objective behavioral metrics — task duration, error rates, and the frequency and type of user intervention — independently of subjective mediation. This supports the position that execution-oriented AI constitutes a qualitatively distinct object of inquiry that requires behavioral, not solely attitudinal, methods of investigation.</p>
<p>Second, the pattern of diminishing marginal returns to autonomy extends the theoretical understanding of how autonomy levels relate to behavioral outcomes beyond the prevailing assumption of monotonicity. The finding that the functional boundary between unsupported and system-supported execution is more behaviorally consequential than the boundary between assisted and fully autonomous execution qualifies the implicit premise that more automation yields proportionally more of its predicted effects. For the task environment examined here, the relevant design question appears to be whether to cross the threshold from unsupported to system-supported execution, not how far beyond that threshold to proceed. This reframing has implications for how the autonomy design space is conceptualized and for how empirical comparisons between automation levels are structured in future research.</p>
</section>
<section id="limitations" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="limitations"><span class="header-section-number">5.4</span> Limitations</h2>
<p>Several limitations qualify the interpretation and generalizability of these findings. The study was conducted within a single controlled experimental setting with a sample drawn from a specific population. Although statistical power was sufficient to detect meaningful between-condition differences, the generalizability of the findings is constrained by the characteristics of the prototype, the participant sample, and the single-session cross-sectional design. Replication with larger and more diverse participant populations, and across repeated exposure to the same autonomy conditions, would clarify the robustness and boundary conditions of the observed effects and allow investigation of adaptation processes that cross-sectional comparisons cannot capture.</p>
<p>The experimental task was a structured, rule-governed workflow with explicitly defined validity constraints. This afforded methodological precision — the effects of autonomy could be isolated under controlled conditions and assessed against objective criteria — but it limits transferability to tasks that are ambiguous, preference-sensitive, or involve consequential and irreversible decisions. In such contexts, the cognitive demands of evaluating system-generated outputs may be substantially higher, the costs of mis-reliance more severe, and the behavioral response to execution autonomy qualitatively different. The present findings are therefore most directly applicable to constrained administrative or configuration-oriented digital workflows.</p>
<p>The exclusive reliance on behavioral log data constitutes both a methodological strength and a limitation. System-generated logs yield objective, reproducible measures of task performance and user action, free from social desirability and retrospective distortion. However, they do not afford access to the cognitive and affective processes through which users experienced the different autonomy conditions. Constructs central to human–automation interaction theory — trust, perceived control, cognitive workload, and situational awareness — were not assessed, making it impossible to attribute the observed behavioral patterns to specific psychological mechanisms. Future work that integrates log-based measures with validated self-report instruments, and potentially with physiological or oculomotor indicators of cognitive engagement, would substantially advance understanding of the mechanisms underlying these effects (Lee &amp; See, 2004; Hoff &amp; Bashir, 2015; Dzindolet et al., 2003).</p>
<p>Finally, the binary operationalization of intervention occurrence proved insensitive in this study due to its near-ceiling distribution. Future research should adopt more granular intervention metrics from the outset, distinguishing interventions by type, magnitude, timing relative to task progression, and relationship to system-generated state changes. Such decomposition would enable a more precise characterization of how users exercise residual control under high-autonomy conditions and would allow researchers to distinguish adaptive from corrective forms of intervention.</p>
</section>
<section id="practical-implications" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="practical-implications"><span class="header-section-number">5.5</span> Practical Implications</h2>
<p>The findings carry implications for the design of AI-supported digital workflows that go beyond simple prescriptions to increase or decrease system autonomy. The consistent performance advantages observed in the system-supported conditions — in particular, the reduction in completion time across the full autonomy gradient and the lower error exposure relative to manual execution — provide evidence that execution autonomy is beneficial in structured, constraint-governed task environments where the system can reliably generate valid outputs. In such settings, shifting execution responsibility to the AI reduces manual burden, decreases error exposure, and lowers the likelihood of task abandonment, outcomes that are practically significant in high-volume, repetitive administrative or configuration-oriented workflows.</p>
<p>However, the near-equivalence of the Assistance and Execution conditions on most outcomes challenges the assumption that full execution autonomy should be the default design target. Assistance-oriented systems — which relieve users of the primary configuration burden while preserving modifiability — may offer a more favorable balance between performance efficiency and user agency across a wide range of deployment contexts. This is consistent with evidence that modifiability increases user willingness to engage with and act on algorithmic outputs (Dietvorst et al., 2018), and with arguments that effective human–AI collaboration does not require maximal delegation but rather appropriate delegation calibrated to task structure, risk, and user context (Miller &amp; Parasuraman, 2007). For systems operating in domains where AI reliability is uncertain, where outcomes are heterogeneous or preference-dependent, or where errors are costly and difficult to reverse, an assistance-level design may capture most of the practical benefit of AI support while maintaining the degree of user control necessary for appropriate oversight.</p>
<p>The shift in intervention type from constructive editing to evaluative override and rejection under higher autonomy conditions also carries specific implications for interface design. Users operating within execution-oriented systems require not proficiency in building valid configurations, but the ability to inspect, comprehend, and challenge system-generated outputs efficiently. This places demands on system transparency — specifically, on whether the rationale for system outputs is communicated in a form that users can evaluate — and on the ergonomic design of review and correction pathways. Systems that generate outputs without accessible explanation, or that do not provide targeted correction mechanisms, may undermine the supervisory role that users continue to perform even under high-autonomy conditions (Endsley, 2017). Transparency and corrective access should therefore be treated not as optional interface features but as functional prerequisites for the supervisory control that the present findings confirm users retain across all autonomy levels.</p>
</section>
<section id="conclusion" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">5.6</span> Conclusion</h2>
<p>This study set out to examine how different levels of AI execution autonomy influence user task performance and intervention behavior in a controlled digital workflow. The results demonstrate that shifting execution authority to an AI system produces measurable improvements in task efficiency and reduces the frequency of user intervention — effects that are most pronounced and consistent in comparisons between unsupported manual execution and system-supported conditions. At the same time, higher autonomy does not remove the user from the interaction process. Instead, it restructures their role: intervention persists across all autonomy levels, but its frequency decreases and its character shifts from active configuration toward evaluative supervision.</p>
<p>These findings extend human–automation interaction research by providing behavioral evidence for execution-oriented AI systems and by qualifying the assumption that autonomy effects are monotonically proportional to the degree of delegation. The near-equivalence of Assistance and Execution conditions across most outcomes suggests that the threshold between unsupported and system-supported execution constitutes the primary behavioral boundary in this experimental context, and that calibrated, modifiable autonomy may often be preferable to unconditional full execution, both from a performance standpoint and from the perspective of maintaining meaningful human control.</p>
<p>Future research should address the mechanisms underlying these behavioral patterns by integrating log-based data with subjective and physiological measures, and should examine how the identified effects generalize across task types, user populations, and deployment contexts in which the stakes, ambiguity, and reversibility of AI-executed decisions differ from those studied here. As AI systems assume greater operational authority across consequential domains, empirically grounded understanding of how users respond to and manage execution autonomy will remain essential to the design of systems that are efficient, transparent, and appropriately controllable.</p>
</section>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<p>Bainbridge, L. (1983). Ironies of automation. <em>Automatica, 19</em>(6), 775–779. https://doi.org/10.1016/0005-1098(83)90046-8</p>
<p>Dietvorst, B. J., Simmons, J. P., &amp; Massey, C. (2015). Algorithm aversion: People erroneously avoid algorithms after seeing them err. <em>Journal of Experimental Psychology: General, 144</em>(1), 114–126. https://doi.org/10.1037/xge0000033</p>
<p>Dietvorst, B. J., Simmons, J. P., &amp; Massey, C. (2018). Overcoming algorithm aversion: People will use imperfect algorithms if they can (even slightly) modify them. <em>Management Science, 64</em>(3), 1155–1170. https://doi.org/10.1287/mnsc.2016.2643</p>
<p>Dzindolet, M. T., Peterson, S. A., Pomranky, R. A., Pierce, L. G., &amp; Beck, H. P. (2003). The role of trust in automation reliance. <em>International Journal of Human-Computer Studies, 58</em>(6), 697–718. https://doi.org/10.1016/S1071-5819(03)00038-7</p>
<p>Endsley, M. R. (2017). From here to autonomy: Lessons learned from human–automation research. <em>Human Factors, 59</em>(1), 5–27. https://doi.org/10.1177/0018720816681350</p>
<p>Hoff, K. A., &amp; Bashir, M. (2015). Trust in automation: Integrating empirical evidence on factors that influence trust. <em>Human Factors, 57</em>(3), 407–434. https://doi.org/10.1177/0018720814547570</p>
<p>Lee, J. D., &amp; See, K. A. (2004). Trust in automation: Designing for appropriate reliance. <em>Human Factors, 46</em>(1), 50–80. https://doi.org/10.1518/hfes.46.1.50_30392</p>
<p>Miller, C. A., &amp; Parasuraman, R. (2003). Beyond levels of automation: An architecture for more flexible human–automation collaboration. <em>Proceedings of the Human Factors and Ergonomics Society Annual Meeting, 47</em>(1), 182–186. https://doi.org/10.1177/154193120304700138</p>
<p>Miller, C. A., &amp; Parasuraman, R. (2007). Designing for flexible interaction between humans and automation: Delegation interfaces for supervisory control. <em>Human Factors, 49</em>(1), 57–75. https://doi.org/10.1518/001872007779598037</p>
<p>Mosier, K. L., &amp; Skitka, L. J. (1999). Automation use and automation bias. <em>Proceedings of the Human Factors and Ergonomics Society Annual Meeting, 43</em>(3), 344–348. https://doi.org/10.1177/154193129904300346</p>
<p>Parasuraman, R., &amp; Riley, V. (1997). Humans and automation: Use, misuse, disuse, abuse. <em>Human Factors, 39</em>(2), 230–253. https://doi.org/10.1518/001872097778543886</p>
<p>Parasuraman, R., Sheridan, T. B., &amp; Wickens, C. D. (2000). A model for types and levels of human interaction with automation. <em>IEEE Transactions on Systems, Man, and Cybernetics-Part A: Systems and Humans, 30</em>(3), 286–297. https://doi.org/10.1109/3468.844354</p>
<p>Parasuraman, R., &amp; Wickens, C. D. (2008). Humans: Still vital after all these years of automation. <em>Human Factors, 50</em>(3), 511–520. https://doi.org/10.1518/001872008X312198</p>
<p>Sarter, N. B., &amp; Woods, D. D. (1995). How in the world did we ever get into that mode? Mode error and awareness in supervisory control. <em>Human Factors, 37</em>(1), 5–19. https://doi.org/10.1518/001872095779049516</p>
<p>Sheridan, T. B., &amp; Verplank, W. L. (1978). <em>Human and computer control of undersea teleoperators</em> (Technical Report). MIT Man-Machine Systems Laboratory.</p>
<p>Wickens, C. D., Li, H., Santamaria, A., Sebok, A., &amp; Sarter, N. B. (2010). Stages and levels of automation: An integrated meta-analysis. <em>Proceedings of the Human Factors and Ergonomics Society Annual Meeting, 54</em>(4), 389–393. https://doi.org/10.1177/154193121005400425</p>
</section>
<section id="declaration-of-independence" class="level1 unnumbered">
<h1 class="unnumbered">Declaration of Independence</h1>
<p>I certify that I have written this thesis independently and without the use of any aids other than those stated. All passages taken verbatim or in spirit from publications or other sources are marked as such.</p>
<p>&nbsp;</p>
<p>Place, date: __________________________</p>
<p>Signature: __________________________</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>